const func = require('./contacts')
func.listContacts()
func.getContactById("C9sjBfCo4UJCWjzBnOtxl")
// func.removeContact("e6ywwRe4jcqxXfCZOj_1e")
func.addContact("Daniel", "daniel@gmail.com", "(453) 435-4830")